# Generated by Django 4.2.17 on 2024-12-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Назва')),
                ('url', models.URLField(verbose_name='Посилання')),
                ('shorted_url', models.URLField(verbose_name='Коротке посилання')),
                ('clicks', models.IntegerField(default=0, verbose_name='Переходи')),
            ],
            options={
                'verbose_name': 'Коротке посилання',
                'verbose_name_plural': 'Короткі посилання',
            },
        ),
    ]
